export const data = [
    {
    "id": "1",
    "sectionName": "Liabilities",
    "paidAmount": "564001",
    "totalAmount": "2070000",
    "remainMonth": "178",
    "remainAmount": "1505999",
    "extraAmount": "919860",
    "investAmount": "121980",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "50",
    "totalMonth": "228",
    "profit": "",
    "year": "2024",
    "endYear": "",
    "section": "",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "2",
    "sectionName": "Investment",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "2024",
    "endYear": "",
    "section": "",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "3",
    "sectionName": "Savings",
    "paidAmount": "",
    "totalAmount": "0",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "2024",
    "endYear": "",
    "section": "",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "4",
    "sectionName": "Money Outflows",
    "paidAmount": "",
    "totalAmount": "83500",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "2024",
    "endYear": "",
    "section": "",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "5",
    "sectionName": "Money Inflows",
    "paidAmount": "",
    "totalAmount": "8000",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "2024",
    "endYear": "",
    "section": "",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "6",
    "sectionName": "Hdfc",
    "paidAmount": "230916",
    "totalAmount": "750000",
    "remainMonth": "46",
    "remainAmount": "519084",
    "extraAmount": "239640",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "14",
    "totalMonth": "60",
    "profit": "",
    "year": "",
    "endYear": "May 2028",
    "section": "Liabilities",
    "emi": "16494",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "7",
    "sectionName": "Icici",
    "paidAmount": "67140",
    "totalAmount": "150000",
    "remainMonth": "40",
    "remainAmount": "82860",
    "extraAmount": "51420",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "20",
    "totalMonth": "60",
    "profit": "",
    "year": "",
    "endYear": "Nov 2027",
    "section": "Liabilities",
    "emi": "3357",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "8",
    "sectionName": "Navi",
    "paidAmount": "141300",
    "totalAmount": "420000",
    "remainMonth": "39",
    "remainAmount": "278700",
    "extraAmount": "333600",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "9",
    "totalMonth": "48",
    "profit": "",
    "year": "",
    "endYear": "Oct 2027",
    "section": "Liabilities",
    "emi": "15700",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "9",
    "sectionName": "Hdfc jumbo",
    "paidAmount": "124645",
    "totalAmount": "750000",
    "remainMonth": "53",
    "remainAmount": "625355",
    "extraAmount": "295200",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "7",
    "totalMonth": "60",
    "profit": "",
    "year": "",
    "endYear": "Dec 2028",
    "section": "Liabilities",
    "emi": "17420",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "10",
    "sectionName": "Parag parikh flexi cap",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "11000",
    "currentInvest": "11374",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "374",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "11",
    "sectionName": "Aditya birla PSU equity",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "45500",
    "currentInvest": "46299",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "799",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "12",
    "sectionName": "HDFC flexi cap SIP",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "500",
    "currentInvest": "514",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "14",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "13",
    "sectionName": "SBI PSU Direct Plan Growth",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "20000",
    "currentInvest": "20341",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "341",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "14",
    "sectionName": "Invesco India PSU Equity",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "20000",
    "currentInvest": "20071",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "71",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "15",
    "sectionName": "Motilal Oswal Midcap Fund",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "18000",
    "currentInvest": "18300",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "300",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "16",
    "sectionName": "Stocks",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "6980",
    "currentInvest": "7000",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "20",
    "year": "19/07/24",
    "endYear": "",
    "section": "Investment",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "17",
    "sectionName": "PF",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Savings",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "18",
    "sectionName": "Idfc saving",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Savings",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "19",
    "sectionName": "Santosh",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "03/03/2023",
    "outMoney": "41000",
    "outPaidMoney": "5000",
    "outRemain": "36000",
    "inMoney": ""
    },
    {
    "id": "20",
    "sectionName": "Santosh(Kamapur)",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "500",
    "outPaidMoney": "",
    "outRemain": "500",
    "inMoney": ""
    },
    {
    "id": "21",
    "sectionName": "Raju",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "28/02/2023",
    "outMoney": "2300",
    "outPaidMoney": "2100",
    "outRemain": "200",
    "inMoney": ""
    },
    {
    "id": "22",
    "sectionName": "Raja dudura",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "24/05/2023",
    "outMoney": "500",
    "outPaidMoney": "300",
    "outRemain": "200",
    "inMoney": ""
    },
    {
    "id": "23",
    "sectionName": "Teyun",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "01/06/2023",
    "outMoney": "2000",
    "outPaidMoney": "2000",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "24",
    "sectionName": "Bulu",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "31/08/2023",
    "outMoney": "300",
    "outPaidMoney": "",
    "outRemain": "300",
    "inMoney": ""
    },
    {
    "id": "25",
    "sectionName": "Gouri",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "1400",
    "outPaidMoney": "",
    "outRemain": "1400",
    "inMoney": ""
    },
    {
    "id": "26",
    "sectionName": "Amana",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "27/09/2023",
    "outMoney": "1000",
    "outPaidMoney": "",
    "outRemain": "1000",
    "inMoney": ""
    },
    {
    "id": "27",
    "sectionName": "",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "3000",
    "outPaidMoney": "",
    "outRemain": "3000",
    "inMoney": ""
    },
    {
    "id": "28",
    "sectionName": "Bikash",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "01/10/2023",
    "outMoney": "500",
    "outPaidMoney": "300",
    "outRemain": "200",
    "inMoney": ""
    },
    {
    "id": "29",
    "sectionName": "chandan c",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "",
    "outMoney": "5500",
    "outPaidMoney": "",
    "outRemain": "5500",
    "inMoney": ""
    },
    {
    "id": "30",
    "sectionName": "Sona",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "15/02/24",
    "outMoney": "2000",
    "outPaidMoney": "",
    "outRemain": "2000",
    "inMoney": ""
    },
    {
    "id": "31",
    "sectionName": "Mamu",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "21/02/24",
    "outMoney": "2000",
    "outPaidMoney": "",
    "outRemain": "2000",
    "inMoney": ""
    },
    {
    "id": "32",
    "sectionName": "Chulu",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "05/03/24",
    "outMoney": "1000",
    "outPaidMoney": "500",
    "outRemain": "500",
    "inMoney": ""
    },
    {
    "id": "33",
    "sectionName": "Dukha",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "02/03/24",
    "outMoney": "200",
    "outPaidMoney": "",
    "outRemain": "200",
    "inMoney": ""
    },
    {
    "id": "34",
    "sectionName": "Rubi",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "04/04/24",
    "outMoney": "11000",
    "outPaidMoney": "",
    "outRemain": "11000",
    "inMoney": ""
    },
    {
    "id": "35",
    "sectionName": "",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "25/07/24",
    "outMoney": "4000",
    "outPaidMoney": "",
    "outRemain": "4000",
    "inMoney": ""
    },
    {
    "id": "36",
    "sectionName": "Bebi",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "10/01/24",
    "outMoney": "10000",
    "outPaidMoney": "",
    "outRemain": "10000",
    "inMoney": ""
    },
    {
    "id": "37",
    "sectionName": "Bebi",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "20/04/24",
    "outMoney": "2000",
    "outPaidMoney": "",
    "outRemain": "2000",
    "inMoney": ""
    },
    {
    "id": "38",
    "sectionName": "Pushpa",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "01/12/23",
    "outMoney": "2500",
    "outPaidMoney": "",
    "outRemain": "",
    "inMoney": ""
    },
    {
    "id": "39",
    "sectionName": "",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "27/07/24",
    "outMoney": "1500",
    "outPaidMoney": "",
    "outRemain": "4000",
    "inMoney": ""
    },
    {
    "id": "40",
    "sectionName": "Sanju-dudura",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "09/05/24",
    "outMoney": "5000",
    "outPaidMoney": "",
    "outRemain": "5000",
    "inMoney": ""
    },
    {
    "id": "41",
    "sectionName": "Muna",
    "paidAmount": "",
    "totalAmount": "",
    "remainMonth": "",
    "remainAmount": "",
    "extraAmount": "",
    "investAmount": "",
    "currentInvest": "",
    "redeem": "",
    "paidMonth": "",
    "totalMonth": "",
    "profit": "",
    "year": "",
    "endYear": "",
    "section": "Money Outflows",
    "emi": "",
    "outMoneyDate": "01/06/24",
    "outMoney": "1000",
    "outPaidMoney": "1000",
    "outRemain": "",
    "inMoney": ""
    }
    ]